[package]
name = "mc-world"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "Blocks, chunks, lighting data structures (no rendering, no network)"

[lints]
workspace = true

[dependencies]
mc-protocol = { version = "0.1.0", path = "../mc-protocol" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
