use std::{
    fs::{self, File, OpenOptions},
    io::{self, Write},
    path::{Path, PathBuf},
};

use super::{PumpkinError, RELEASE};

const MARKER: &str = ".mc-client-pumpkin";

pub(super) fn prepare(directory: &Path, port: u16) -> Result<(PathBuf, File), PumpkinError> {
    let name =
        directory.file_name().ok_or(PumpkinError::InvalidSession("missing directory name"))?;
    let parent = directory
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."))
        .canonicalize()?;
    if parent.ancestors().any(|path| {
        path.join(".git").exists()
            && !parent
                .strip_prefix(path)
                .is_ok_and(|relative| relative.components().any(|part| part.as_os_str() == ".data"))
    }) {
        return Err(PumpkinError::InvalidSession(
            "session must be outside a Git checkout or under .data",
        ));
    }
    let directory = parent.join(name);
    let new = match fs::create_dir(&directory) {
        Ok(()) => true,
        Err(error) if error.kind() == io::ErrorKind::AlreadyExists => false,
        Err(error) => return Err(error.into()),
    };
    if fs::symlink_metadata(&directory)?.file_type().is_symlink() {
        return Err(PumpkinError::InvalidSession("session directory is a symlink"));
    }
    if directory.join(".git").exists() {
        return Err(PumpkinError::InvalidSession("session must be outside a Git checkout"));
    }
    let marker = directory.join(MARKER);
    if new {
        let mut file = OpenOptions::new().write(true).create_new(true).open(&marker)?;
        file.write_all(RELEASE.as_bytes())?;
        file.sync_all()?;
    } else if fs::symlink_metadata(&marker).map_or(true, |m| !m.is_file())
        || fs::read_to_string(&marker)? != RELEASE
    {
        return Err(PumpkinError::InvalidSession("missing or incompatible ownership marker"));
    }
    let lock = managed_file(&directory, ".session.lock")?;
    lock.try_lock().map_err(|_| PumpkinError::SessionBusy)?;
    for name in ["world", "plugins"] {
        if directory.join(name).symlink_metadata().is_ok_and(|m| m.file_type().is_symlink()) {
            return Err(PumpkinError::InvalidSession("world/plugin path is a symlink"));
        }
    }
    let mut config = managed_file(&directory, "pumpkin.toml")?;
    config.set_len(0)?;
    config.write_all(configuration(port).as_bytes())?;
    config.sync_all()?;
    Ok((directory, lock))
}

pub(super) fn managed_file(directory: &Path, name: &str) -> Result<File, PumpkinError> {
    let path = directory.join(name);
    match path.symlink_metadata() {
        Ok(metadata) if !metadata.is_file() => {
            return Err(PumpkinError::InvalidSession("managed path is not a regular file"));
        }
        Err(error) if error.kind() != io::ErrorKind::NotFound => return Err(error.into()),
        _ => {}
    }
    Ok(OpenOptions::new().read(true).write(true).create(true).truncate(false).open(path)?)
}

fn configuration(port: u16) -> String {
    // Original configuration using documented field names for release 8d0d0d3.
    format!(
        r#"# Generated by mc-client; changes are replaced on the next managed launch.
seed = "776"
default_gamemode = "Creative"
default_level_name = "world"
allow_chat_reports = false
use_favicon = false

[world]
autosave_ticks = 6000

[networking.java]
enabled = true
address = "127.0.0.1:{port}"
motd = "{}"
online_mode = false
encryption = false
max_players = 1
view_distance = 4
simulation_distance = 4

[networking.java.authentication]
enabled = false

[networking.bedrock]
enabled = false

[networking.query]
enabled = false

[networking.rcon]
enabled = false

[networking.proxy]
enabled = false

[networking.lan_broadcast]
enabled = false

[plugins]
enabled = false

[commands]
use_console = true
use_tty = false

[logging]
color = false
"#,
        identity(port)
    )
}

pub(super) fn identity(port: u16) -> String {
    format!("mc-client-local-{}-{port}", std::process::id())
}
