[package]
name = "mc-render"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "wgpu renderer (Vulkan/Metal/DX12/GL). No game logic."

[lints]
workspace = true

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"] }
glam = "0.33.6"
image = { version = "0.25.10", default-features = false, features = ["png"] }
mc-world = { version = "0.1.0", path = "../mc-world" }
pollster = "1.0.1"
serde_json = "1.0.151"
thiserror = "2.0.20"
wgpu = "30.0.1"
winit = "0.30.13"

[dev-dependencies]
mc-protocol = { path = "../mc-protocol" }
