[package]
name = "mc-client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "Game loop, 20 TPS tick, input, audio, UI orchestration"

[lints]
workspace = true

[dependencies]
mc-protocol = { version = "0.1.0", path = "../mc-protocol" }
mc-launcher = { version = "0.1.0", path = "../mc-launcher" }
bytes = "1"
clap = { version = "4", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["io-util", "macros", "net", "rt", "time", "signal"] }
mc-world = { version = "0.1.0", path = "../mc-world" }
mc-render = { version = "0.1.0", path = "../mc-render" }
glam = "0.33.6"

[dev-dependencies]
tempfile = "3"
